---
title: "FlowGrid"
author: "Xinyi Lin"
date: "4/9/2021"
output: html_document
---

Generate large scRNA-seq data for FlowGrid.

The overall sample size should be around 500k

Three types of data:

* cell clusters with the same size

* 20 big clusters and 10 small clusters

* 10 big clusters(>5%), 10 medium clusters(1%-5%) and 10 small clusters(0.1%-0.5%; 500-2500)

The cluster size is defined based on [Park's paper, 2018](https://pubmed.ncbi.nlm.nih.gov/29622724/)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r,message=FALSE,warning=FALSE}
library(splatter)
library(Seurat)
library(tidyverse)
```

## 30 clusters with even sizes

```{r}
## simulate cells pool setting
cluster_num = 30
prob = rep(1/cluster_num, cluster_num)
batch_size = 500000
de_prob = rep(0.3, cluster_num)
setresolu = 0.5
```

```{r}
## simulate cells pool process
set.seed(123)
#params = readRDS("./data/mnnCT7params.rds")
params <- newSplatParams()
sim <- splatSimulate(params, batchCells = round(batch_size*prob), group.prob = prob, de.prob = de_prob)
#sim <- splatSimulate(batchCells = round(batch_size*prob), group.prob = prob, method = "groups", verbose = FALSE)
sim_mat <- counts(sim)
origLabels = sim@colData@listData$Group
```

### plot the UMAP of clusters

```{r}
sim_mat = sim_mat[,sample(1:dim(sim_mat)[2], 0.01*dim(sim_mat)[2])]
seuratObj <- CreateSeuratObject(counts = sim_mat, project="Splatter")
seuratObj <- NormalizeData(seuratObj, verbose = FALSE)
seuratObj <- FindVariableFeatures(seuratObj, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
seuratObj <- ScaleData(seuratObj)
seuratObj <- RunPCA(seuratObj, features = VariableFeatures(object = seuratObj))
seuratObj <- FindNeighbors(seuratObj, dims = 1:30, verbose = FALSE)
seuratObj <- FindClusters(seuratObj, resolution = setresolu, verbose = FALSE)
seuratObj <- RunUMAP(seuratObj, dims = 1:30, verbose = FALSE)
DimPlot(seuratObj, reduction = "umap")
```

### save as h5ad

```{r}
zellkonverter::writeH5AD(sim, "/storage/holab/linxy/others/flowgrid_sim1.h5ad")
```


```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}
```

